### ISSUE TITLE
Support Sanic blueprints with Sanic Limiter

### ISSUE THREAD

**Issue by d0ugal** [bohea/sanic-limiter#2]
I've built my app around blueprints, so I'd like to add limits to the blueprints - but I can't figure out if it possible.

Thanks!

**Comment by d0ugal** [comment]
Sorry for the noise, I think I figured it out.

```
@bp.listener('after_server_start')
async def init_limiter(app, loop):
    limiter.init_app(app)
```

**Comment by bohea** [comment]
bp is not supported for now
but this is a good idea
will you start a issue for that？
在2017年03月22日 04:44，Dougal Matthews 写道:

I've built my app around blueprints, so I'd like to add limits to the blueprints - but I can't figure out if it possible.

Thanks!

**Comment by d0ugal** [comment]
I have reopened this issue and changed the title - hope that is good enough!

**Comment by bohea** [comment]
need update doc

**Comment by d0ugal** [comment]
Thank you! :smile:
