### ISSUE TITLE
Doesn't appear to throttle for endpoint args

### ISSUE THREAD

**Issue by psiofxt** [bohea/sanic-limiter#7]
In testing, I'm noticing an endpoint pattern such as `/index/<id>` doesn't get throttled with sanic-limiter. I've been using this for well over a month now and it works great with endpoints like `/health`.

```python
from sanic import Sanic, response
from sanic_limiter import Limiter, get_remote_address

app = Sanic()
limiter = Limiter(app, global_limits=['10 per second', '1 per day'], key_func=get_remote_address)


@app.route('/index/<id>', methods=['GET'])
@limiter.limit("2 per hour")
async def index(request, id):
    return response.json({'id': id})


@app.route('/home', methods=['GET'])
@limiter.limit("2 per hour")
async def home(request):
    return response.json({'success': 'you are home'})


app.run(host='127.0.0.1', port=8000, access_log=True)
```

The above sample does not get throttled for the first endpoint but gets throttled for the second. 

Versions:
`sanic==0.7.0`
`sanic-limiter==0.1.3`

**Comment by psiofxt** [comment]
@bohea Do you mind if I open a PR with a small workaround I made in `extensions.py`? 

It's not perfect at all and I was hoping you'd be able to have a better method:
`/index/1000` will get throttled but then `/index/2000` will work until throttled. Now `/index/` is throttled with `1000` and `2000` as params but I'm trying to make it so the uri pattern, `/index/<id>` is throttled.

**Comment by bohea** [comment]
@psiofxt  a PR is welcome

I think a string or callable(like key_func) can be given by users which will replace the endpoint

**Comment by psiofxt** [comment]
@bohea I see what you are saying, but I'm unsure how to get `Limiter` to even recognize an endpoint because something like `/index/<id>` isn't in `app.router.routes_static`. 

See here: https://github.com/bohea/sanic-limiter/blob/master/sanic_limiter/extension.py#L155

This is the workaround I did to try to match the URI: https://github.com/psiofxt/sanic-limiter/commit/332f85b2d931dc2269ede4ae2feea797eeed4b9c

**Comment by bohea** [comment]
@psiofxt  I see what's your point

try #8 

```python
from sanic import Sanic, response
from sanic_limiter import Limiter, get_remote_address

app = Sanic()
limiter = Limiter(app, global_limits=['10 per second', '1 per day'], key_func=get_remote_address)

@app.route('/index/<id>', methods=['GET'])
@limiter.shared_limit("2 per hour", scope='index_pattern')
async def index(request, id):
    return response.json({'id': id})
```

**Comment by psiofxt** [comment]
@bohea That is much simpler and works perfectly, thank you. I didn't know that the `request` would be able to be pulled from `self.app.router.get(...)` so easily. 

Issue solved :)

**Comment by bohea** [comment]
Thank you for opening this issue.
Feel free to make a pull request or issue if you find any bugs

**Comment by psiofxt** [comment]
No prob, appreciate the help. Is this change up to date via `pip`? @bohea

**Comment by gpapin** [comment]
As of today it's still not up to date with pip install unfortunately
